apiVersion : apps/v1
kind: Deployment
metadata:
  name: reactcode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactcode
  template:
    metadata:
      labels:
        app: reactcode 
    spec:
      containers:
        - name: reactcode 
          image: dhawalepraful1310/reactcode
          ports:
          - containerPort: 3000
